---
- name: Install CMS
  hosts: cloud
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install PHP MySQL module
      apt:
        name: php-mysql
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership for WordPress files
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create MySQL database for WordPress
      mysql_db:
        name: wordpress
        state: present

    - name: Create MySQL user for WordPress
      mysql_user:
        name: wp_user
        password: password
        host: localhost
        priv: "wordpress.*:ALL"
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Check Apache status
      command: systemctl status apache2
      register: apache_status
      ignore_errors: yes

    - name: Check MySQL status
      command: systemctl status mysql
      register: mysql_status
      ignore_errors: yes

    - name: Display Apache status
      debug:
        var: apache_status.stdout

    - name: Display MySQL status
      debug:
        var: mysql_status.stdout