- name: Make Files With `loop`
  file:
    path: "/tmp/{{ item }}"
    state: touch
  loop:
    - file1.txt
    - file2.txt
    - file3.txt

- name: Add User With `with_items`
  become: yes
  user:
    name: "{{ item }}"
    state: present
  with_items:
    - user1
    - user2
    - user3
